project:
  type: website
  output-dir: _site


website:
  search: true          # adds a search box to the site so readers can search your pages.
  announcement:         # banner across the top of every page
    content: "Final proposal due **22 Jul**"
    type: warning       # info, warning, or danger
    dismissable: true   # adds a "x" to deleted it
  page-footer:          # text at the bottom of every page
    center: "StatProg2 — LMU Munich"
  title: "Happiness ㋡"
  navbar:
    left:
      - href: project_proposal.qmd
        text: Home
      - href: data.qmd
        text: "Our dataset"
      - href: format.qmd
        text: "Presentation formats"
      - href: about.qmd
        text: "About this site"
      - href: group-reflection.qmd
        text: "Group reflection"
      - href: CONTRIBUTING.qmd
        text: "Contributions"
    right:
      - icon: github
        href: https://github.com/Youta-droid/Stat_Project   #link to your repo
        aria-label: GitHub   # screen-readers announce "GitHub"


format:                    # "Make the code box PRETTY"
  html:                    # render pages as HTML.
    theme:                 # visual Bootstrap theme
     light: minty
     dark: superhero
    css: styles.css        # load own custom CSS file for extra styling on top of the theme.
    toc: true              # show a table of contents on each page
    code-fold: true        # code chunks are collapsed by default behind a toggle
    code-summary: "Show code"
    code-overflow: scroll  # or wrap
    code-line-numbers: true
    code-copy: hover       # copy button on hover
    code-tools: true       # show/hide all code menu


execute:           # "RUN the code and handle output"
  echo: false      # show source code
  eval: true       # run code
  output: true     # include results
  warning: false   # suppress warnings
  error: false     # halt on errors
  cache: false     # don't cache by default
  freeze: auto     # re-run only if source changes


editor: visual

